apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: selenium-grid
  repo: https://www.selenium.dev/docker-selenium
  releaseName: selenium-grid
  namespace: selenium
  valuesFile: ./selenium-values.yaml

resources:
- namespace.yaml

patches:
- target:
    kind: Deployment
    name: ".*"
  patch: |-
    - op: add
      path: /spec/template/spec/initContainers
      value: []

components:
- ../../wireguard-sidecar
