apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selenium

helmCharts:
- name: selenium-grid
  repo: https://www.selenium.dev/docker-selenium
  releaseName: selenium-grid
  namespace: selenium
  valuesFile: selenium-values.yaml

resources:
- namespace.yaml
- wireguard-secret.yaml

components:
- https://github.com/lur1an/kustomize-wireguard-sidecar
