tls:
  enabled: false

edgeNode:
  enabled: false
  deploymentEnabled: false

basicAuth:
  enabled: false

ingress:
  enabled: false

firefoxNode:
  enabled: false
  deploymentEnabled: false

chromeNode:
  labels:
    wireguard-sidecar: enable
  replicas: 1
  ports:
  - 5900
  - 7900
  nameOverride: node-chromium
  imageName: node-chromium
  extraEnvironmentVariables:
  - name: SE_VNC_PASSWORD
    value: deez
  - name: SE_NODE_MAX_SESSIONS
    value: "3"
  - name: SE_NODE_OVERRIDE_MAX_SESSIONS
    value: "true"
  initContainers: []

ingress:
  enabled: false
