apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: doesNotMatter
spec:
  template:
    spec:
      volumes:
      - name: wireguard-config
        emptyDir: {}
      - name: wireguard-secret
        secret:
          secretName: wireguard-secret

      initContainers:
      - name: copy-wireguard-config
        image: busybox
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - sh
        - -c
        - |
          echo copying /etc/wireguard-secret/wg0-$POD_NAME.conf to config volume
          cat /etc/wireguard-secret/wg0-$POD_NAME.conf > /config/wg0.conf
          sysctl -w net.ipv4.ip_forward=1
          chmod 400 /config/wg0.conf
        volumeMounts:
        - name: wireguard-config
          mountPath: /config
        - name: wireguard-secret
          mountPath: /etc/wireguard-secret
          readOnly: true
      - name: wireguard
        image: ghcr.io/linuxserver/wireguard:latest
        imagePullPolicy: IfNotPresent
        restartPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
        ports:
        - containerPort: 51820
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: Etc/UTC
        - name: ALLOWEDIPS
          value: "0.0.0.0/0"
        - name: LOG_CONFS
          value: "true"
        volumeMounts:
        - name: wireguard-config
          mountPath: /config
