apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    labelSelector: wireguard-sidecar=enable
  path: patches/deployment/sidecar.yaml

- target:
    kind: Deployment
    labelSelector: wireguard-sidecar=enable
  path: patches/deployment/init.yaml

- target:
    kind: StatefulSet
    labelSelector: wireguard-sidecar=enable
  path: patches/statefulset/init.yaml

- target:
    kind: StatefulSet
    labelSelector: wireguard-sidecar=enable
  path: patches/statefulset/sidecar.yaml

- target:
    kind: CronJob
    labelSelector: wireguard-sidecar=enable
  path: patches/cronjob/sidecar.yaml
