apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    labelSelector: wireguard-sidecar=enable
  path: patches/deployment.yaml

- target:
    kind: StatefulSet
    labelSelector: wireguard-sidecar=enable
  path: patches/statefulset.yaml

- target:
    kind: CronJob
    labelSelector: wireguard-sidecar=enable
  path: patches/cronjob.yaml
