apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hello-world
  namespace: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: testcontainers/helloworld
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /deeznuts
          name: deeznuts
      restartPolicy: Always

      initContainers: []

      volumes:
      - emptyDir: {}
        name: deeznuts

