apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-world
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- wireguard-secret.yaml

components:
- https://github.com/lur1an/kustomize-wireguard-sidecar
