apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: doesNotMatter
spec:
  template:
    spec:
      volumes:
      - name: wireguard-config
        emptyDir: {}
      - name: wireguard-secret
        secret:
          secretName: wireguard-secret

      initContainers:
      - name: copy-wireguard-config
        image: busybox
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - sh
        - -c
        - |
          echo copying /etc/wireguard-secret/wg0-$POD_NAME.conf to config volume
          cat /etc/wireguard-secret/wg0-$POD_NAME.conf > /config/wg0.conf
          sysctl -w net.ipv4.ip_forward=1
          chmod 400 /config/wg0.conf
        volumeMounts:
        - name: wireguard-config
          mountPath: /config
        - name: wireguard-secret
          mountPath: /etc/wireguard-secret
          readOnly: true

