- op: add
  path: /spec/template/spec/initContainers/-
  value:
    name: copy-wireguard-config
    image: busybox
    command:
    - sh
    - -c
    - |
      cat /etc/wireguard-secret/wg0.conf > /config/wg0.conf
      sysctl -w net.ipv4.ip_forward=1
      chmod 400 /config/wg0.conf
    volumeMounts:
    - name: wireguard-config
      mountPath: /config
    - name: wireguard-secret
      mountPath: /etc/wireguard-secret
      readOnly: true

